import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GoogleTagManager from "../components/GoogleTagManager"; // cuidado com o nome do arquivo!
import "./globals.css";
import {Poppins,League_Spartan } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-poppins" });
const league = League_Spartan({ subsets: ["latin"], variable: "--font-league" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable} 
          ${league.variable} 
          antialiased
        `}
      >
        {/* Google Tag Manager */}
        <GoogleTagManager gtmId="GTM-TZ827BTR" />

        {/* Conteúdo da aplicação */}
        {children}
      </body>
    </html>
  );
}
